#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def requestVote(self, term, candidate_id, last_log_index, last_log_term):
        """
        Parameters:
         - term
         - candidate_id
         - last_log_index
         - last_log_term

        """
        pass

    def appendEntry(self, term, leader_id, prev_log_index, prev_log_term, entry, leader_commit):
        """
        Parameters:
         - term
         - leader_id
         - prev_log_index
         - prev_log_term
         - entry
         - leader_commit

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def requestVote(self, term, candidate_id, last_log_index, last_log_term):
        """
        Parameters:
         - term
         - candidate_id
         - last_log_index
         - last_log_term

        """
        self.send_requestVote(term, candidate_id, last_log_index, last_log_term)
        return self.recv_requestVote()

    def send_requestVote(self, term, candidate_id, last_log_index, last_log_term):
        self._oprot.writeMessageBegin('requestVote', TMessageType.CALL, self._seqid)
        args = requestVote_args()
        args.term = term
        args.candidate_id = candidate_id
        args.last_log_index = last_log_index
        args.last_log_term = last_log_term
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_requestVote(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = requestVote_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        raise TApplicationException(TApplicationException.MISSING_RESULT, "requestVote failed: unknown result")

    def appendEntry(self, term, leader_id, prev_log_index, prev_log_term, entry, leader_commit):
        """
        Parameters:
         - term
         - leader_id
         - prev_log_index
         - prev_log_term
         - entry
         - leader_commit

        """
        self.send_appendEntry(term, leader_id, prev_log_index, prev_log_term, entry, leader_commit)
        return self.recv_appendEntry()

    def send_appendEntry(self, term, leader_id, prev_log_index, prev_log_term, entry, leader_commit):
        self._oprot.writeMessageBegin('appendEntry', TMessageType.CALL, self._seqid)
        args = appendEntry_args()
        args.term = term
        args.leader_id = leader_id
        args.prev_log_index = prev_log_index
        args.prev_log_term = prev_log_term
        args.entry = entry
        args.leader_commit = leader_commit
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_appendEntry(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = appendEntry_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        raise TApplicationException(TApplicationException.MISSING_RESULT, "appendEntry failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["requestVote"] = Processor.process_requestVote
        self._processMap["appendEntry"] = Processor.process_appendEntry

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_requestVote(self, seqid, iprot, oprot):
        args = requestVote_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = requestVote_result()
        try:
            result.success = self._handler.requestVote(args.term, args.candidate_id, args.last_log_index, args.last_log_term)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("requestVote", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_appendEntry(self, seqid, iprot, oprot):
        args = appendEntry_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = appendEntry_result()
        try:
            result.success = self._handler.appendEntry(args.term, args.leader_id, args.prev_log_index, args.prev_log_term, args.entry, args.leader_commit)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("appendEntry", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class requestVote_args(object):
    """
    Attributes:
     - term
     - candidate_id
     - last_log_index
     - last_log_term

    """


    def __init__(self, term=None, candidate_id=None, last_log_index=None, last_log_term=None,):
        self.term = term
        self.candidate_id = candidate_id
        self.last_log_index = last_log_index
        self.last_log_term = last_log_term

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.term = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.candidate_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.last_log_index = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.last_log_term = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('requestVote_args')
        if self.term is not None:
            oprot.writeFieldBegin('term', TType.I32, 1)
            oprot.writeI32(self.term)
            oprot.writeFieldEnd()
        if self.candidate_id is not None:
            oprot.writeFieldBegin('candidate_id', TType.I32, 2)
            oprot.writeI32(self.candidate_id)
            oprot.writeFieldEnd()
        if self.last_log_index is not None:
            oprot.writeFieldBegin('last_log_index', TType.I32, 3)
            oprot.writeI32(self.last_log_index)
            oprot.writeFieldEnd()
        if self.last_log_term is not None:
            oprot.writeFieldBegin('last_log_term', TType.I32, 4)
            oprot.writeI32(self.last_log_term)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(requestVote_args)
requestVote_args.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'term', None, None, ),  # 1
    (2, TType.I32, 'candidate_id', None, None, ),  # 2
    (3, TType.I32, 'last_log_index', None, None, ),  # 3
    (4, TType.I32, 'last_log_term', None, None, ),  # 4
)


class requestVote_result(object):
    """
    Attributes:
     - success

    """


    def __init__(self, success=None,):
        self.success = success

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = Ballot()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('requestVote_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(requestVote_result)
requestVote_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [Ballot, None], None, ),  # 0
)


class appendEntry_args(object):
    """
    Attributes:
     - term
     - leader_id
     - prev_log_index
     - prev_log_term
     - entry
     - leader_commit

    """


    def __init__(self, term=None, leader_id=None, prev_log_index=None, prev_log_term=None, entry=None, leader_commit=None,):
        self.term = term
        self.leader_id = leader_id
        self.prev_log_index = prev_log_index
        self.prev_log_term = prev_log_term
        self.entry = entry
        self.leader_commit = leader_commit

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.term = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.leader_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.prev_log_index = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.prev_log_term = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.entry = Entry()
                    self.entry.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.I32:
                    self.leader_commit = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('appendEntry_args')
        if self.term is not None:
            oprot.writeFieldBegin('term', TType.I32, 1)
            oprot.writeI32(self.term)
            oprot.writeFieldEnd()
        if self.leader_id is not None:
            oprot.writeFieldBegin('leader_id', TType.I32, 2)
            oprot.writeI32(self.leader_id)
            oprot.writeFieldEnd()
        if self.prev_log_index is not None:
            oprot.writeFieldBegin('prev_log_index', TType.I32, 3)
            oprot.writeI32(self.prev_log_index)
            oprot.writeFieldEnd()
        if self.prev_log_term is not None:
            oprot.writeFieldBegin('prev_log_term', TType.I32, 4)
            oprot.writeI32(self.prev_log_term)
            oprot.writeFieldEnd()
        if self.entry is not None:
            oprot.writeFieldBegin('entry', TType.STRUCT, 5)
            self.entry.write(oprot)
            oprot.writeFieldEnd()
        if self.leader_commit is not None:
            oprot.writeFieldBegin('leader_commit', TType.I32, 6)
            oprot.writeI32(self.leader_commit)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(appendEntry_args)
appendEntry_args.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'term', None, None, ),  # 1
    (2, TType.I32, 'leader_id', None, None, ),  # 2
    (3, TType.I32, 'prev_log_index', None, None, ),  # 3
    (4, TType.I32, 'prev_log_term', None, None, ),  # 4
    (5, TType.STRUCT, 'entry', [Entry, None], None, ),  # 5
    (6, TType.I32, 'leader_commit', None, None, ),  # 6
)


class appendEntry_result(object):
    """
    Attributes:
     - success

    """


    def __init__(self, success=None,):
        self.success = success

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = Response()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('appendEntry_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(appendEntry_result)
appendEntry_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [Response, None], None, ),  # 0
)
fix_spec(all_structs)
del all_structs

