#ifndef CONSTANTS_H
#define CONSTANTS_H

inline const char* MIN_ELECTION_TIMEOUT_ENV_VAR_NAME = "RANDOM_TIMEOUT_MIN_MS";
inline const char* MAX_ELECTION_TIMEOUT_ENV_VAR_NAME = "RANDOM_TIMEOUT_MAX_MS";
inline const char* HEARTBEAT_TICK_ENV_VAR_NAME = "HEARTBEAT_TICK_MS";
inline const char* RPC_TIMEOUT_ENV_VAR_NAME = "RPC_TIMEOUT_MS";
inline const char* RPC_RETRY_TIMEOUT_MIN_ENV_VAR_NAME = "MIN_RPC_RETRY_TIMEOUT";
inline const char* SNAPSHOT_FILE_ENV_VAR_NAME = "SNAPSHOT_FILE";
inline const char* MAX_ALLOWED_LOG_SIZE_ENV_VAR_NAME = "MAX_ALLOWED_LOG_SIZE";

#endif
