#!/bin/bash

rm *.log

echo -n "127.0.0.1:5000" > .leader
echo -n "4" > .request

./replica.py 127.0.0.1 5000 &
./replica.py 127.0.0.1 5001 &
./replica.py 127.0.0.1 5002 &

sleep 30

pgrep replica.py | while read -r line ; do
   kill -9 $line
done


