/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "replicaservice_constants.h"



const replicaserviceConstants g_replicaservice_constants;

replicaserviceConstants::replicaserviceConstants() {
}



