/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef replicaservice_CONSTANTS_H
#define replicaservice_CONSTANTS_H

#include "replicaservice_types.h"



class replicaserviceConstants {
 public:
  replicaserviceConstants();

};

extern const replicaserviceConstants g_replicaservice_constants;



#endif
